import { ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { HeroSlider } from '../components/HeroSlider'; import { CompanyVideo } from '../components/CompanyVideo'; import { SEO } from '../components/SEO'; import { ServicePreview } from '../components/ServicePreview'; import { Partners } from '../components/Partners'; import { ContactBand } from '../components/ContactBand'; import { LocationSection } from '../components/LocationSection'
import { featuredServices } from '../data/services'; import { industries } from '../data/company'; import { assetUrl } from '../utils/assets'
const homeFeaturedServices=featuredServices.slice(0,2)
export function HomePage(){return <><SEO title="Objektbetreuung & Facility Services Rhein-Main" description="Perlas unterstützt Hausverwaltungen und Unternehmen mit professioneller Objektbetreuung und Facility Services für Gewerbeimmobilien im Rhein-Main-Gebiet."/><HeroSlider/><CompanyVideo/>
<Partners/>
<section className="section home-services"><div className="section-head"><div><span className="eyebrow">Unsere Leistungen</span><h2>Alles, was Ihr Objekt braucht.</h2></div><p>Professionelle Objektbetreuung und Gebäudeservices für Hausverwaltungen und Unternehmen im Rhein-Main-Gebiet – einzeln beauftragt oder sinnvoll gebündelt.</p></div><ServicePreview items={homeFeaturedServices}/><div className="center-link"><Link className="button" to="/leistungen">Alle Facility Services ansehen <ArrowRight/></Link></div></section>
<section className="positioning"><div className="positioning-image"><img src={assetUrl('images/home/objektbetreuung-kontrolle.jpg')} alt="Perlas Mitarbeitende prüfen und dokumentieren eine Auffälligkeit an einer Gewerbeimmobilie" loading="lazy"/></div><div className="positioning-copy"><span className="eyebrow light">Ganzheitliche Objektbetreuung</span><h2>Das gesamte Objekt im Blick.</h2><p className="lead">Unsere Facility Services unterstützen ein verlässliches Facility Management: Wir erkennen Auffälligkeiten frühzeitig, dokumentieren Entwicklungen und informieren Auftraggeber, bevor aus kleinen Problemen größere Schäden entstehen.</p><div className="positioning-principles" aria-label="Unser Leistungsversprechen"><article><span>01</span><h3>Mitdenken</h3><p>Wir erkennen Auffälligkeiten frühzeitig und geben relevante Beobachtungen aktiv weiter.</p></article><article><span>02</span><h3>Dokumentieren</h3><p>Digitale Nachweise und Fotos machen Feststellungen nachvollziehbar.</p></article><article><span>03</span><h3>Verantwortung übernehmen</h3><p>Wir behandeln betreute Objekte mit derselben Sorgfalt, als wären es unsere eigenen.</p></article></div><Link className="button button-white" to="/ueber-uns">Perlas kennenlernen <ArrowRight/></Link></div></section>
<section className="documentation-band"><div><span className="eyebrow light">Digitale Dokumentation</span><h2>Transparenz statt Zettelwirtschaft.</h2></div><p>Digitale Leistungsnachweise, Fotodokumentationen und strukturierte Objektmappen schaffen einen klaren Überblick. Hausverwaltungen und Unternehmen können nachvollziehen, was vor Ort durchgeführt und festgestellt wurde.</p></section>
<section className="section industries-home"><div className="section-head"><div><span className="eyebrow">Einsatzbereiche</span><h2>Wir verstehen, was Ihre Branche braucht.</h2></div><Link className="simple-link" to="/branchen">Alle Branchen <ArrowRight/></Link></div><div className="industry-feature"><img src={assetUrl(industries[0][3])} alt={industries[0][1]} loading="lazy"/><div><span>{industries[0][1]}</span><h3>Services für Immobilien, die jeden Tag funktionieren müssen.</h3><p>{industries[0][2]}</p><Link className="simple-link" to="/branchen">Einsatzbereiche ansehen <ArrowRight/></Link></div></div><div className="industry-links">{industries.slice(1,5).map(i=><Link to="/branchen" key={i[0]}>{i[1]}<ArrowRight/></Link>)}</div></section>
{/* Kennzahlen vor dem Livegang kundenseitig bestätigen. */}
<section className="home-facts" aria-label="Kennzahlen von Perlas"><article><strong>Seit 1999</strong><span>aktiv</span></article><article><strong>Über 15</strong><span>Unternehmen vertrauen auf Perlas</span></article><article><strong>500+</strong><span>Objekte werden betreut / gepflegt</span></article></section>
<LocationSection/><ContactBand/></>}
