import { ArrowRight, Check } from 'lucide-react'
import { Link } from 'react-router-dom'
import { HeroSlider } from '../components/HeroSlider'; import { SEO } from '../components/SEO'; import { ServicePreview } from '../components/ServicePreview'; import { BlogPreview } from '../components/BlogPreview'; import { Team } from '../components/Team'; import { Partners } from '../components/Partners'; import { ContactBand } from '../components/ContactBand'
import { featuredServices } from '../data/services'; import { posts } from '../data/blog'; import { industries } from '../data/company'; import { assetUrl } from '../utils/assets'
export function HomePage(){return <><SEO title="Objektbetreuung & Facility Services" description="Perlas betreut Immobilien und Gewerbeobjekte mit professionellen Facility Services, Reinigung, Außenpflege und persönlicher Verantwortung."/><HeroSlider/>
<section className="company-portrait" aria-label="Perlas Objektbetreuung"><img src={assetUrl('images/perlas-team-concept.png')} alt="Team von Perlas vor einem Firmenfahrzeug"/></section>
<section className="section home-services"><div className="section-head"><div><span className="eyebrow">Unsere Leistungen</span><h2>Alles, was Ihr Objekt braucht.</h2></div><p>Professionell organisiert, persönlich betreut und passend zu Ihren Anforderungen.</p></div><ServicePreview items={featuredServices.slice(0,2)}/><div className="center-link"><Link className="button" to="/leistungen">Alle Leistungen anzeigen <ArrowRight/></Link></div></section>
<section className="positioning"><div className="positioning-image"><img src={assetUrl('images/perlas-praxis-concept.png')} alt="Perlas Team bei der Objektbetreuung"/></div><div className="positioning-copy"><span className="eyebrow light">Mehr als Hausmeisterservice</span><h2>Ein Partner. Klare Verantwortung.</h2><p className="lead">Perlas ist Ihr ganzheitlicher Partner für Objektbetreuung und Facility Services. Persönliche Nähe und professionelle Strukturen prägen unsere Zusammenarbeit.</p><ul><li><Check/>Zentraler Ansprechpartner</li><li><Check/>Koordinierte Services</li><li><Check/>Dokumentierte Qualität</li><li><Check/>Kurze Kommunikationswege</li></ul><Link className="button button-white" to="/ueber-uns">Perlas kennenlernen <ArrowRight/></Link></div></section>
<section className="section industries-home"><div className="section-head"><div><span className="eyebrow">Einsatzbereiche</span><h2>Verstanden, was Ihre Branche braucht.</h2></div><Link className="simple-link" to="/branchen">Alle Branchen <ArrowRight/></Link></div><div className="industry-feature"><img src={assetUrl(industries[0][3])} alt={industries[0][1]}/><div><span>{industries[0][1]}</span><h3>Services für Immobilien, die jeden Tag funktionieren müssen.</h3><p>{industries[0][2]}</p><Link className="simple-link" to="/branchen">Einsatzbereiche ansehen <ArrowRight/></Link></div></div><div className="industry-links">{industries.slice(1,5).map(i=><Link to="/branchen" key={i[0]}>{i[1]}<ArrowRight/></Link>)}</div></section>
<Team/><section className="career" id="karriere"><div className="career-img"><img src={assetUrl('images/perlas-team-concept.png')} alt="Team von Perlas auf einem Gewerbecampus"/></div><div className="career-copy"><span className="eyebrow light">Karriere bei Perlas</span><h2>Gemeinsam mehr bewegen.</h2><p>Bei uns zählen Einsatz, Verlässlichkeit und das Miteinander. Mit Berufserfahrung oder als Quereinstieg machen wir Ihnen die Bewerbung unkompliziert.</p><Link className="button button-white" to="/karriere">Karriere bei Perlas <ArrowRight/></Link></div></section>
<section className="section"><div className="section-head"><div><span className="eyebrow">Wissen rund ums Objekt</span><h2>Praxiswissen. Klar erklärt.</h2></div><Link className="simple-link" to="/blog">Alle Artikel <ArrowRight/></Link></div><BlogPreview items={posts.slice(0,3)}/></section><Partners/><ContactBand/></>}
