import { SEO } from '../components/SEO'
import type { ReactNode } from 'react'

function LegalPage({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <><SEO title={title} description={`${title} von Perla’s Objektbetreuung.`}/><header className="legal-hero"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1></header><article className="legal-content">{children}</article></>}

export function ImprintPage(){return <LegalPage eyebrow="Rechtliche Informationen" title="Impressum">
  <section><h2>Angaben gemäß § 5 DDG</h2><address>Perla’s Objektbetreuung GmbH &amp; Co. KG<br/>Hauptstraße 1<br/>65843 Sulzbach (Taunus)<br/>Deutschland</address><p>Telefon: <a href="tel:+491776867145">+49 177 68 67 145</a><br/>E-Mail: <a href="mailto:mail@perlas.de">mail@perlas.de</a></p></section>
  <section><h2>Vertretungsberechtigte</h2><p>Geschäftsführung: Paolo Perla</p></section>
  <section><h2>Registereintrag</h2><p>Registergericht: Amtsgericht Frankfurt am Main<br/>Handelsregister: HRA 46445</p></section>
  <section><h2>Kammerzugehörigkeit</h2><p>Handwerkskammer Rhein-Main</p></section>
  <section><h2>Umsatzsteuer</h2><p>Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: DE 278829312</p></section>
  <section><h2>Angaben zur Berufshaftpflichtversicherung</h2><p>Versicherer: Helvetia Versicherungen<br/>Sitz / Anschrift: Filialdirektion Frankfurt, Postfach 101059, 60010 Frankfurt am Main<br/>Geltungsraum: Europa sowie außereuropäische Gebiete, die zum Geltungsbereich des Vertrages über die Europäische Union gehören</p></section>
  <section><h2>Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV</h2><p>Paolo Perla<br/>Hauptstraße 1, 65843 Sulzbach (Taunus)</p></section>
  <section><h2>Haftungsausschluss</h2><h3>Haftung für Inhalte</h3><p>Wir erstellen die Inhalte dieser Website mit größter Sorgfalt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte übernehmen wir jedoch keine Gewähr. Als Diensteanbieter sind wir nach den allgemeinen Gesetzen für eigene Inhalte verantwortlich. Eine Haftung ist erst ab Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entsprechender Rechtsverletzungen entfernen wir diese Inhalte umgehend.</p><h3>Haftung für Links</h3><p>Unsere Website enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber verantwortlich. Bei Bekanntwerden von Rechtsverletzungen entfernen wir derartige Links umgehend.</p></section>
  <section><h2>Urheberrecht</h2><p>Die durch uns erstellten Inhalte und Werke auf dieser Website unterliegen dem deutschen Urheberrecht. Downloads und Kopien sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Sofern Inhalte nicht von uns erstellt wurden, werden die Urheberrechte Dritter beachtet.</p></section>
  <section><h2>Verbraucherstreitbeilegung</h2><p>Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p></section>
 </LegalPage>}

export function PrivacyPage(){return <LegalPage eyebrow="Stand: 07.01.2026" title="Datenschutzerklärung">
  <section><h2>1. Verantwortlicher</h2><address>Perla’s Objektbetreuungs-GmbH &amp; Co. KG<br/>Hauptstraße 1, 65843 Sulzbach (Taunus), Deutschland<br/>Telefon: <a href="tel:+491776867145">+49 177 68 67 145</a><br/>E-Mail: <a href="mailto:mail@perlas.de">mail@perlas.de</a></address></section>
  <section><h2>2. Allgemeine Hinweise zur Datenverarbeitung</h2><p>Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung einer funktionsfähigen Website sowie unserer Inhalte/Leistungen erforderlich ist oder du eingewilligt hast.</p><p>Rechtsgrundlagen je nach Fall:</p><ul><li>Art. 6 Abs. 1 lit. a DSGVO (Einwilligung)</li><li>Art. 6 Abs. 1 lit. b DSGVO (Vertrag / vorvertragliche Maßnahmen)</li><li>Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse, z. B. Betrieb/Sicherheit)</li></ul><p>Zusätzlich gilt für Cookies/ähnliche Technologien in Deutschland § 25 TDDDG (Einwilligung bzw. technische Erforderlichkeit).</p></section>
  <section><h2>3. Hosting und Server-Logfiles</h2><p>Unsere Website wird technisch betrieben/gehostet über:</p><address>SIMpress Media (Markus Pusch)<br/>Dunant Ring 21<br/>65936 Frankfurt am Main<br/>Deutschland</address><p>Beim Aufruf der Website werden durch den Server automatisch folgende Daten verarbeitet:</p><ul><li>IP-Adresse (ggf. gekürzt)</li><li>Datum/Uhrzeit</li><li>aufgerufene Seite/Datei</li><li>Browsertyp/-version</li><li>Betriebssystem</li><li>Referrer-URL</li><li>Hostname</li></ul><p><strong>Zweck:</strong><br/>technische Bereitstellung, Stabilität und Sicherheit, z. B. Missbrauchserkennung.</p><p><strong>Rechtsgrundlage:</strong><br/>Art. 6 Abs. 1 lit. f DSGVO.</p><p>Logfiles werden nur so lange gespeichert, wie es für Betrieb/Sicherheit erforderlich ist.</p></section>
  <section><h2>4. Cookies, Consent-Management und deine Auswahl</h2><p>Wir verwenden Cookies/ähnliche Technologien:</p><p><strong>Notwendig/Essentiell:</strong><br/>für den Betrieb der Website erforderlich und immer aktiv.</p><p><strong>Optional, z. B. Statistik/Marketing:</strong><br/>nur nach deiner Einwilligung.</p><p>Wir setzen ein Consent-Tool (Cookie-Banner) ein.</p><p>Dort kannst du:</p><ul><li>Einwilligungen erteilen oder ablehnen</li><li>deine Auswahl jederzeit ändern oder widerrufen</li></ul><p>Rechtsgrundlagen:</p><p>§ 25 Abs. 1 TDDDG + Art. 6 Abs. 1 lit. a DSGVO für optionale Cookies/Tracking</p><p>§ 25 Abs. 2 TDDDG + Art. 6 Abs. 1 lit. f DSGVO für essentielle Cookies</p></section>
  <section><h2>5. Kontaktaufnahme (E-Mail / Telefon)</h2><p>Wenn du uns kontaktierst, verarbeiten wir deine Angaben zur Bearbeitung der Anfrage.</p><p><strong>Rechtsgrundlage:</strong><br/>Art. 6 Abs. 1 lit. b DSGVO oder Art. 6 Abs. 1 lit. f DSGVO.</p><p><strong>Speicherdauer:</strong><br/>solange erforderlich zur Bearbeitung, ggf. gesetzliche Aufbewahrungspflichten.</p></section>
  <section><h2>6. Kontaktformular (WPForms)</h2><p>Wenn du unser Kontaktformular nutzt, verarbeiten wir die von dir eingegebenen Daten, z. B. Name, E-Mail und Nachricht, zur Bearbeitung deiner Anfrage.</p><p><strong>Rechtsgrundlage:</strong><br/>Art. 6 Abs. 1 lit. b DSGVO oder Art. 6 Abs. 1 lit. f DSGVO.</p><p><strong>Speicherdauer:</strong><br/>solange erforderlich zur Bearbeitung, ggf. gesetzliche Aufbewahrungspflichten.</p></section>
  <section><h2>7. Spam-Schutz (Google reCAPTCHA)</h2><p>Zum Schutz vor Spam/automatisierten Anfragen kann Google reCAPTCHA eingesetzt werden.</p><p>Dabei können technische Daten, u. a. IP-Adresse, Geräte-/Browserdaten und Interaktionen, an Google übermittelt werden.</p><p><strong>Anbieter:</strong><br/>Google Ireland Limited, Dublin, Irland.</p><p><strong>Rechtsgrundlage:</strong><br/>Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO i. V. m. § 25 Abs. 1 TDDDG.</p><p><strong>Hinweis:</strong><br/>Wenn du nicht einwilligst, kann das Kontaktformular ggf. eingeschränkt sein.</p></section>
  <section><h2>8. Google Tag Manager (GTM)</h2><p>Wir verwenden Google Tag Manager, um Website-Tags zentral zu verwalten.</p><p>Der Tag Manager selbst erstellt in der Regel keine Nutzerprofile, kann aber technische Daten, z. B. IP-Adresse, an Google übermitteln und dient dem Ausspielen weiterer Tools, z. B. Google Analytics.</p><p><strong>Anbieter:</strong><br/>Google Ireland Limited, Dublin, Irland.</p><p><strong>Rechtsgrundlage:</strong><br/>Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO i. V. m. § 25 Abs. 1 TDDDG.</p><p>GTM wird erst nach Einwilligung geladen.</p></section>
  <section><h2>9. Google Analytics (GA4)</h2><p>Wir verwenden Google Analytics 4, um die Nutzung unserer Website auszuwerten und unser Angebot zu verbessern.</p><p>Dabei können u. a. verarbeitet werden:</p><ul><li>Nutzungs-/Interaktionsdaten, z. B. Seitenaufrufe, Klicks</li><li>Geräte-/Browserinformationen</li><li>ungefährer Standort</li><li>technische Kennungen</li></ul><p>Google verarbeitet nach eigenen Angaben im GA4-Kontext IP-Adressen so, dass sie nicht dauerhaft protokolliert/gespeichert werden, insbesondere für EU-Nutzer.</p><p><strong>Anbieter:</strong><br/>Google Ireland Limited, Dublin, Irland.</p><p><strong>Rechtsgrundlage:</strong><br/>Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO i. V. m. § 25 Abs. 1 TDDDG.</p><p><strong>Widerruf:</strong><br/>Du kannst deine Einwilligung jederzeit über die Cookie-Einstellungen widerrufen.</p><p><strong>Drittlandtransfer:</strong><br/>Es kann nicht ausgeschlossen werden, dass Daten an Google-Server außerhalb der EU/EWR, insbesondere USA, übermittelt werden.</p><p>Google nutzt hierfür geeignete Garantien, z. B. EU-Standardvertragsklauseln und/oder anerkannte Zertifizierungen.</p></section>
  <section><h2>10. Google Consent Mode (optional)</h2><p>Sofern aktiviert, verwenden wir Google Consent Mode, um deine Cookie-Auswahl technisch an Google-Dienste zu übermitteln, damit sich diese entsprechend deiner Einwilligung verhalten.</p><p>Der Consent Mode ersetzt kein Cookie-Banner, sondern arbeitet mit diesem zusammen.</p></section>
  <section><h2>11. Bewerbungen / „Offene Stellen“ (JOIN)</h2><p>Bewerbungen laufen über JOIN (join.com).</p><p>Wenn du auf unserer Website auf „Offene Stellen“ klickst oder ein JOIN-Element nutzt, wirst du ggf. auf Dienste von JOIN weitergeleitet bzw. es können Inhalte von JOIN geladen werden.</p><p>Dabei gelten die Datenschutzhinweise von JOIN.</p><p><strong>Rechtsgrundlage für die Verlinkung:</strong><br/>Art. 6 Abs. 1 lit. f DSGVO.</p><p>Wenn du dich bewirbst, erfolgt die Datenverarbeitung im Bewerbungsprozess nach den JOIN-Hinweisen sowie unseren internen Bewerbungsprozessen.</p></section>
  <section><h2>12. Empfänger / Auftragsverarbeiter</h2><p>Wir setzen Dienstleister ein, die Daten in unserem Auftrag verarbeiten, z. B. Hosting und Formular-Tools.</p><p>Diese sind vertraglich auf Datenschutz verpflichtet gemäß Art. 28 DSGVO, soweit erforderlich.</p></section>
  <section><h2>13. Speicherdauer</h2><p>Wir speichern personenbezogene Daten nur so lange, wie es für die jeweiligen Zwecke erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen.</p></section>
  <section><h2>14. Deine Rechte</h2><p>Du hast das Recht auf:</p><ul><li>Auskunft (Art. 15 DSGVO)</li><li>Berichtigung (Art. 16 DSGVO)</li><li>Löschung (Art. 17 DSGVO)</li><li>Einschränkung der Verarbeitung (Art. 18 DSGVO)</li><li>Datenübertragbarkeit (Art. 20 DSGVO)</li><li>Widerspruch gegen Verarbeitung auf Basis von Art. 6 Abs. 1 lit. f DSGVO (Art. 21 DSGVO)</li><li>Widerruf einer Einwilligung (Art. 7 Abs. 3 DSGVO) jederzeit mit Wirkung für die Zukunft</li></ul><p>Außerdem hast du das Recht, dich bei einer Datenschutz-Aufsichtsbehörde zu beschweren (Art. 77 DSGVO).</p></section>
  <section><h2>15. Sicherheitsmaßnahmen</h2><p>Wir setzen technische und organisatorische Maßnahmen ein, um deine Daten gegen Verlust, Manipulation oder unberechtigte Zugriffe zu schützen.</p></section>
  <section><h2>16. Änderungen dieser Datenschutzerklärung</h2><p>Wir passen diese Datenschutzerklärung an, wenn sich Rechtslage, Technik oder unsere Verarbeitungsvorgänge ändern.</p></section>
 </LegalPage>}
