import { ArrowRight, Mail, Phone } from 'lucide-react'
import { Link } from 'react-router-dom'
import { SEO } from '../components/SEO'
import { PageHero } from '../components/PageHero'
import { Partners } from '../components/Partners'

export function ReferencesPage(){return <><SEO title="Referenzen & Partner" description="Partnerschaften und Projektfelder von Perlas Facility Services."/><PageHero kicker="Referenzen" title="Vertrauen entsteht durch verlässliche Zusammenarbeit." text="Entdecken Sie unsere langfristigen Partnerschaften und ausgewählten Einsatzfelder."/><Partners/></>}
export function ContactPage(){return <><SEO title="Kontakt" description="Kontaktieren Sie Perlas für Objektbetreuung, Gebäudereinigung, Außenpflege und Facility Services."/><PageHero kicker="Kontakt" title="Wie können wir Ihr Objekt unterstützen?" text="Erzählen Sie uns von Ihrer Immobilie und Ihren Anforderungen. Wir melden uns persönlich bei Ihnen."/><section className="contact-page section"><div><h2>Direkt erreichbar</h2><a href="tel:+491776867145"><Phone/>0177 6867145</a><a href="mailto:mail@perlas.de"><Mail/>mail@perlas.de</a></div><form onSubmit={e=>e.preventDefault()}><label>Name<input name="name" autoComplete="name"/></label><label>Unternehmen<input name="company" autoComplete="organization"/></label><label>E-Mail<input type="email" name="email" autoComplete="email"/></label><label>Ihr Anliegen<textarea name="message" rows={5}/></label><button className="button" type="submit">Anfrage vorbereiten <ArrowRight/></button></form></section></>}
export function NotFoundPage(){return <section className="not-found"><span className="eyebrow">404</span><h1>Diese Seite wurde nicht gefunden.</h1><p>Vielleicht finden Sie über unsere Startseite den passenden Einstieg.</p><Link className="button" to="/">Zur Startseite <ArrowRight/></Link></section>}
