import { useEffect, useRef, useState } from 'react'
import { Menu, X, Phone, ArrowUpRight, ChevronDown } from 'lucide-react'
import { Link, NavLink, useLocation } from 'react-router-dom'

const services=[['Objektbetreuung','objektbetreuung'],['Gebäudereinigung','gebaeudereinigung'],['Außenanlagenpflege','aussenanlagenpflege'],['Winterdienst','winterdienst'],['Facility Services','facility-services']]

export function Header(){
 const [open,setOpen]=useState(false); const [servicesOpen,setServicesOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const menuButton=useRef<HTMLButtonElement>(null); const {pathname}=useLocation()
 const close=()=>{setOpen(false);setServicesOpen(false)}
 useEffect(()=>{const fn=()=>setScrolled(scrollY>24);fn();addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[])
 useEffect(()=>{close()},[pathname])
 useEffect(()=>{document.body.classList.toggle('nav-open',open);const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&open){close();menuButton.current?.focus()}};document.addEventListener('keydown',escape);return()=>{document.body.classList.remove('nav-open');document.removeEventListener('keydown',escape)}},[open])
 return <header className={`header ${scrolled?'is-scrolled':''}`}><a className="skip" href="#main">Zum Inhalt</a><div className="nav-wrap"><Link to="/" className="brand" aria-label="Perlas Startseite" onClick={close}><span className="brand-mark">P</span><span>PERLAS<small>FACILITY SERVICES</small></span></Link><nav id="main-navigation" className={open?'open':''} aria-label="Hauptnavigation"><NavLink to="/" onClick={close}>Startseite</NavLink><div className={`nav-dropdown ${servicesOpen?'mobile-open':''}`}><div className="nav-dropdown-main"><NavLink to="/leistungen" onClick={close}>Leistungen</NavLink><button type="button" onClick={()=>setServicesOpen(value=>!value)} aria-label="Untermenü Leistungen umschalten" aria-expanded={servicesOpen}><ChevronDown/></button></div><div className="nav-submenu">{services.map(([name,slug])=><Link key={slug} to={`/leistungen/${slug}`} onClick={close}>{name}</Link>)}<Link to="/leistungen" onClick={close}><b>Alle Leistungen</b></Link></div></div><NavLink to="/branchen" onClick={close}>Branchen</NavLink><NavLink to="/ueber-uns" onClick={close}>Über uns</NavLink><NavLink to="/karriere" onClick={close}>Karriere</NavLink><NavLink to="/blog" onClick={close}>Blog</NavLink><NavLink to="/kontakt" onClick={close}>Kontakt</NavLink><a className="mobile-phone" href="tel:+491776867145" onClick={close}><Phone/> 0177 6867145</a></nav><div className="nav-actions"><a className="phone" href="tel:+491776867145"><Phone/> 0177 6867145</a><Link className="button button-small" to="/kontakt">Anfrage stellen <ArrowUpRight/></Link><button ref={menuButton} className="menu" type="button" onClick={()=>setOpen(value=>!value)} aria-label={open?'Menü schließen':'Menü öffnen'} aria-controls="main-navigation" aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></div></header>
}
